#file: noinspection YAMLDuplicatedKeys
spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:com/acautomaton/forum/mapper/*.xml, classpath:com/acautomaton/forum/mapper/**/*.xml
  configuration:
    auto-mapping-unknown-column-behavior: warning
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleteFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

mybatis-plus-join:
  banner: false

pagehelper:
  reasonable: true
  auto-dialect: true
  support-methods-arguments: true

### !!! below should be in application-dev.yml !!! ###
server:
  port: 9000

logging:
  config: classpath:log4j2-dev.yml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DATABASE_NAME?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: DATABASE_USERNAME
    password: DATABASE_PASSWORD
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      password: REDIS_PASSWORD
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
      jedis:
        pool:
          max-idle: 10
          min-idle: 5
          max-wait: 5000ms
  mail:
    host: SMTP_HOST_DOMAIN
    username: SMTP_USERNAME
    password: SMTP_PASSWORD
    port: 465
    default-encoding: UTF-8
    protocol: smtps

project:
  jwt:
    secretkey: JWT_SECRETKEY
    timeoutDays: 7
  tencent:
    cos:
      secretId: SECRET_ID
      secretKey: SECRET_KEY
      bucketName: BUCKET_NAME
      bucketResourcePrepend: BUCKET_RESOURCE_PREPEND
      region: REGION
      objectUrlPrepend: OBJECT_URL_PREPEND
  alibaba:
    alipay:
      appPrivateKey: PRIVATE_KEY
      alipayPublicKey: PUBLIC_KEY
      serverUrl: SERVER_URL
      appId: APP_ID
  cors:
    allow-origin: http://localhost:9001